name: Deploy Docker images

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  sonarcloud:
    uses: ./.github/workflows/sonarcloud.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  eslint:
    uses: ./.github/workflows/eslint.yml

  tsc:
    uses: ./.github/workflows/tsc.yml

  backend:
    runs-on: ubuntu-latest
    needs: [sonarcloud, eslint, tsc]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_URL }}/stilipsdue-backend
          platforms: linux/amd64

  frontend:
    runs-on: ubuntu-latest
    needs: [sonarcloud, eslint, tsc]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_URL }}/stilipsdue-frontend
          platforms: linux/amd64
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL }}
            VITE_AUTH0_DOMAIN=${{ secrets.VITE_AUTH0_DOMAIN }}
            VITE_AUTH0_AUDIENCE=${{ secrets.VITE_AUTH0_AUDIENCE }}
            VITE_AUTH0_SCOPE=${{ secrets.VITE_AUTH0_SCOPE }}
            VITE_AUTH0_CLIENTID=${{ secrets.VITE_AUTH0_CLIENTID }}
