name: ESLint

on:
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_call:

jobs:
  check_errors:
    strategy:
      matrix:
        target_application:
          - name: Frontend
            path: app
            additional_dependencies: eslint-plugin-react@latest
          - name: Backend
            path: server

    name: ${{ matrix.target_application.name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          yarn add \
            typescript \
            eslint@8.10.0 \
            @microsoft/eslint-formatter-sarif@2.1.7 \
            @typescript-eslint/eslint-plugin@latest \
            @typescript-eslint/parser \
            ${{ matrix.target_application.additional_dependencies }}

      - name: Run ESLint
        run: |
          npx eslint \
            --config ${{ matrix.target_application.path }}/.eslintrc.cjs \
            --ext .js,.jsx,.ts,.tsx \
            --format @microsoft/eslint-formatter-sarif \
            --output-file eslint-results.sarif \
            ${{ matrix.target_application.path }}

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
        if: ${{ always() }}
