name: SonarCloud Analysis
on:
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_call:
    secrets:
      SONAR_TOKEN:
        description: "SonarCloud token"
        required: true

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
