name: TSC

on:
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_call:

  workflow_dispatch:

jobs:
  check_errors:
    strategy:
      matrix:
        target_application:
          - name: Frontend
            path: app
          - name: Backend
            path: server

    name: ${{ matrix.target_application.name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install depdendencies
        run: |
          yarn add tsc typescript
          yarn --cwd ${{ matrix.target_application.path }}

      - name: Run TSC
        run: npx tsc --project ${{ matrix.target_application.path }}/tsconfig.json --noEmit --pretty
