name: TSC

on:
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_call:

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install depdendencies
        run: |
          yarn add tsc
          yarn add typescript
          yarn --cwd app

      - name: Run TSC
        run: npx tsc --project app/tsconfig.json --noEmit --pretty

  backend:
    name: Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install depdendencies
        run: |
          yarn add tsc
          yarn add typescript
          yarn --cwd server

      - name: Run TSC
        run: npx tsc --project server/tsconfig.json --noEmit --pretty
